name: CI

on:
  push:
    branches:
      - 'feature-*'  # Triggers on feature branches

jobs:
  build-and-merge:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: homestead
          MYSQL_USER: root
          MYSQL_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5

      selenium:
        image: seleniarm/standalone-chromium:latest
        ports:
          - 4444:4444
        options: --health-cmd="curl -f http://localhost:4444/wd/hub/status || exit 1" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Run unit tests
        run: npm test -- --coverage

      - name: Build project
        run: npm run build

      - name: Set Git user
        run: |
          git config --global user.name 'zishan07cse'
          git config --global user.email 'zishan07csecuet@gmail.com'

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout dev branch
        run: git checkout dev

      - name: Merge feature branch into dev
        run: |
          # Extract the branch name from the ref
          branch_name=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')

          # Check if the branch name is valid
          if [ -z "$branch_name" ]; then
            echo "Branch name is empty. Exiting."
            exit 1
          fi

          # Ensure dev branch is up-to-date
          git pull origin dev

          # Merge the feature branch into dev
          git merge origin/$branch_name --no-ff -m "Merge feature branch '$branch_name' into dev"

          # Push changes to dev
          git push origin dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Selenium tests
        run: npm run test:selenium
        env:
          SELENIUM_URL: http://localhost:4444/wd/hub
